import { Outfit } from "next/font/google";
import "./globals.css";
import { ThemeProvider as NextThemesProvider } from 'next-themes'

import { ConvexClientProvider } from "./_providers/ConvexClientProvider";
import { Toaster } from "@/components/ui/sonner";

const outfit = Outfit({
  subsets: ['latin']
})

export const metadata = {
  title: "Vid AI Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={outfit.className}
      >
        <ConvexClientProvider>
          <NextThemesProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster  position="top-center" reverseOrder={false} />
          </NextThemesProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
