import { Outfit } from "next/font/google";
import "./globals.css";
import ThemeProvider from "../components/theme-provider";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

const outfit = Outfit({
  subsets: ['latin']
})

export const metadata = {
  title: "Vid AI Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>


      <html lang="en" suppressHydrationWarning>
        <body
          className={outfit.className}
        >
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
