import { Outfit } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./provider";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { ThemeProvider as NextThemesProvider } from 'next-themes'

import { ConvexClientProvider } from "./_providers/ConvexClientProvider";

const outfit = Outfit({
  subsets: ['latin']
})

export const metadata = {
  title: "Vid AI Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={outfit.className}
      >
        <ConvexClientProvider>
          <NextThemesProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </NextThemesProvider>
        </ConvexClientProvider>
      </body>
    </html>
    // </ClerkProvider>
  );
}
